/** The enemy archive and Protocol Assimilation data models, generated by `tools/data/import.mjs`. */

import type { StatArray } from "./tdoll";

/** The nine rank bars the game's own archive draws for an enemy, in display order. Each is a 0 to 7 rating, not a stat. */
export type EnemyRankKey = "power" | "health" | "accuracy" | "evasion" | "rateOfFire" | "armor" | "speed" | "range" | "tenacity";

/** One value per rank bar. */
export type EnemyRankValues = Record<EnemyRankKey, number>;

/** The stat keys an enemy's base deployment carries, in display order. */
export type EnemyStatKey = "hp" | "damage" | "accuracy" | "evasion" | "rateOfFire" | "armor" | "armorPiercing" | "range" | "speed" | "number";

/** One value per enemy stat. */
export type EnemyStatValues = Record<EnemyStatKey, number>;

/** One of an enemy's own skills, as the archive words it. These carry no levels, unlike a doll or Assimilation skill. */
export interface EnemySkill {
	/** Official English skill name. */
	name: string;
	/** What the skill does, in one or two sentences. */
	description: string;
}

/** One enemy as the index lists it. */
export interface Enemy {
	/** Upstream `enemy_illustration.sub_id`, unique across the archive and the key the stat rows join on. */
	id: number;
	/** Upstream `enemy_illustration.id`, shared by every variant of the same enemy and what a captured unit points at. */
	familyId: number;
	/** Official English name, such as "Vespid". */
	name: string;
	/** The game's unit code, such as "BossArchitect", which names its asset bundles. */
	code: string;
	/** Faction name, one of the entries in `EnemyData.factions`. */
	faction: string;
	/** Whether this is one of the named boss and Ringleader tier rather than a mob. */
	boss: boolean;
	/** Whether Protocol Assimilation has a playable unit for this enemy's family. */
	capturable: boolean;
	/** The archive's own rank bars, which are how two enemies are meant to be compared. */
	ranks: EnemyRankValues;
}

/** The page-only half of one enemy, kept out of the index download. */
export interface EnemyDetails {
	/** A variant's own name when it differs from the enemy's, such as an Elite version. Null when they are the same. */
	subName: string | null;
	/** The archive's lore blurb. */
	introduce: string;
	/** The archive's advice on how to fight this enemy. */
	counter: string;
	/** The credited voice actor, or an empty string when the archive names none. */
	voiceActor: string;
	/** The organisation the enemy belongs to, such as "Isolated Testing Ground". Null when upstream records none. */
	organisation: string | null;
	/** Base deployment stats, not the numbers met on a map. Null for the few enemies with no stat row at all. */
	baseStats: EnemyStatValues | null;
	/** The level the base stats are quoted at. Null when there are no base stats. */
	baseStatsLevel: number | null;
	/** The enemy's own skills, which may be empty for a plain mob. */
	skills: EnemySkill[];
}

/** The generated `enemies.json`. */
export interface EnemyData {
	/** The faction names present, in display order, for the filter chips. */
	factions: string[];
	/** Every enemy, in archive order. */
	items: Enemy[];
}

/** The generated `enemy-details.json`, keyed by stringified enemy id. */
export type EnemyDetailsData = Record<string, EnemyDetails>;

// //////////////////////////////////////////////////////////////////////////////////////////////////
// //////////////////////////////////////////////////////////////////////////////////////////////////
// Protocol Assimilation

/** The stat keys a captured unit's growth is expressed in, in display order. */
export type AssimilationStatKey = "hp" | "damage" | "accuracy" | "evasion" | "rateOfFire" | "armor";

/** One value per Assimilation stat. */
export type AssimilationStatValues = Record<AssimilationStatKey, number>;

/** What one class of captured unit shares. */
export interface AssimilationClass {
	/** The class's base rate per stat, before the unit's own percentages. */
	baseRates: AssimilationStatValues;
	/** The chance a capture attempt succeeds, in percent. */
	captureRate: number;
	/** The chance a guaranteed capture succeeds, in percent. */
	guaranteedRate: number;
	/** The highest level each of the four skill slots reaches, in slot order. A zero means the class has no such slot. */
	skillLevels: number[];
}

/** The game constants a captured unit's stats are worked out from. Shipped as the game's inputs, since the site does not compute a stat line. */
export interface AssimilationConstants {
	/** The highest level a captured unit reaches, from `sangvis_lv_max`. */
	maxLevel: number;
	/** Added to the unit's level before scaling, from `sangvis_base_lv`. */
	baseLevel: number;
	/** The level each star rank unlocks at, indexed from 0. */
	starUnlockLevels: number[];
	/** Each star rank's multiplier per stat, in percent, indexed from 0. */
	starRates: AssimilationStatValues[];
	/** Each class's shared values, keyed by class name. */
	classes: Record<string, AssimilationClass>;
}

/** One strategic chip a Ringleader can equip. */
export interface AssimilationChip {
	/** Upstream `sangvis_chip` id. */
	id: number;
	/** Official English chip name. */
	name: string;
	/** What the chip does. */
	description: string;
	/** Which slot type the chip fits, matching the entries in a unit's `chipSlots`. */
	type: number;
}

/** One of a captured unit's skills. Each `statN` fills the matching `#N` in the description, one value per level. */
export interface AssimilationSkill {
	/** Which `sangvis` field the skill came from, such as `skill_advance`. */
	slot: string;
	/** Official English skill name. */
	name: string;
	/** "Passive", or the cooldown before the first use, such as "6s". Absent on a mission skill. */
	initial_cooldown?: string;
	/** Cooldown at each level, absent on passive skills. */
	cooldown?: StatArray;
	/** Planning cost at each level, present only on a mission skill. */
	cost?: StatArray;
	/** The description with `#N` placeholders. */
	description: string;
	/** How many `statN` arrays the skill has. */
	number_of_stats: number;
	/** Placeholder values at each level. */
	[stat: `stat${number}`]: StatArray | undefined;
}

/** One Protocol Assimilation unit: an enemy a player can capture and field. */
export interface AssimilationUnit {
	/** Upstream `sangvis` id. */
	id: number;
	/** The enemy family this unit is captured from, matching `Enemy.familyId`. */
	familyId: number;
	/** Official English name, such as "Scarecrow". */
	name: string;
	/** The game's unit code, which names its asset bundles. */
	code: string;
	/** Class name, one of the entries in `AssimilationData.classes`. */
	className: string;
	/** Star rarity as the game shows it, 3 to 5. */
	stars: number;
	/** Trait names such as "Armored" or "Ranged", which decide what counters the unit. */
	traits: string[];
	/** The unit's lore blurb, which reads from the player's side rather than the archive's. */
	introduce: string;
	/** The unit's own share of each stat, in percent against its class's base rate. */
	ratios: AssimilationStatValues;
	/** Armour penetration. */
	armorPiercing: number;
	/** Critical hit chance, in percent. */
	crit: number;
	/** Critical hit damage, in percent. */
	critDamage: number;
	/** Planning points the unit costs to deploy. */
	apCost: number;
	/** The chip types each strategic chip slot accepts. Empty for every class but Ringleader. */
	chipSlots: number[][];
	/** The unit's skills, in slot order. */
	skills: AssimilationSkill[];
}

/** The generated `assimilation.json`. */
export interface AssimilationData {
	/** The class names, from the strongest tier down. */
	classes: string[];
	/** Constants shared by every captured unit. */
	constants: AssimilationConstants;
	/** Every strategic chip. */
	chips: AssimilationChip[];
	/** Every playable unit, one per capturable enemy family. */
	units: AssimilationUnit[];
}
