/** The equipment data model, generated by `tools/data/import.mjs`. */

/** Per-level stat values for levels 0 to 10, formatted like `"+24"` or `"+3~5"`. */
export type EquipmentStats = Record<string, string[]>;

/** One equipment type, used for the filter chips. */
export interface EquipmentType {
	/** Stable key the items are grouped under, such as `opticalSight`. */
	key: string;
	/** Official English type name. */
	label: string;
}

/** A doll an exclusive item belongs to. */
export interface EquipmentDoll {
	/** Base doll id. */
	id: number;
	/** True when only the doll's Mod can equip it. */
	mod: boolean;
}

/** One piece of equipment as generated. */
export interface RawEquipment {
	/** Upstream equipment id. */
	id: number;
	/** Official English name. */
	name: string;
	/** Rarity, 2 to 6. */
	rarity: number;
	/** True for equipment restricted to specific dolls. */
	exclusive: boolean;
	/** Doll types that can equip it, such as `SMG`. Empty for exclusive items. */
	usable: string[];
	/** The dolls an exclusive item belongs to. Empty otherwise. */
	dolls: EquipmentDoll[];
	/** Flavour text. */
	description: string;
	/** Stat values by stat key. */
	stats: EquipmentStats;
	/** Build time in seconds when Equipment Productions can give the item, otherwise null. */
	buildSeconds: number | null;
}

/** Equipment with its icon URL resolved. */
export interface Equipment extends RawEquipment {
	/** Absolute icon URL, or null when no icon is hosted yet. */
	image: string | null;
}
