/** The Fairy data model, generated by `tools/data/import.mjs`. */

import type { StatArray } from "./tdoll";

/** The five stat keys every Fairy has, in display order. */
export type FairyStatKey = "damage" | "accuracy" | "evasion" | "armor" | "critDamage";

/** One value per Fairy stat. */
export type FairyStatValues = Record<FairyStatKey, number>;

/** The game constants every Fairy's stats are worked out from. */
export interface FairyConstants {
	/** The highest level a Fairy reaches, 100. */
	maxLevel: number;
	/** Each stat's growth curve as `[atLevelOne, perLevel]`, from `game_config_info`'s `fairy_<field>_grow`. */
	grow: Record<FairyStatKey, [number, number]>;
	/** The level each star rank needs, index 0 is 1 star, from `fairy_quality_need_level`. */
	starLevels: number[];
	/** Star ranks grouped by art form, from `fairy_image_type`. */
	forms: number[][];
}

/** One Fairy talent and its effect text. */
export interface FairyTalent {
	/** Upstream `fairy_talent` id, also the `skill_group_id` its effect text is read from. */
	id: number;
	/** Official English name. */
	name: string;
	/** 0 for Special, 1 for Tier I, 2 for Tier II. */
	rank: number;
	/** The effect text at its lowest level. */
	description: string;
}

/** A Fairy's skill, battle or strategy, in the same shape as a doll skill. Each `statN` fills the matching `#N` in the description. */
export interface FairySkill {
	/** Official English skill name. */
	name: string;
	/** "Passive", or the cooldown before the first use, such as "1s". Battle skills only: `mission_skill_config` has no matching field. */
	initial_cooldown?: string;
	/** Cooldown at each level, absent on passive battle skills. Turns for a strategy skill. */
	cooldown?: StatArray;
	/** Command point cost at each level, strategy skills only. */
	cost?: StatArray;
	/** The description with `#N` placeholders. */
	description: string;
	/** How many `statN` arrays the skill has. */
	number_of_stats: number;
	/** Placeholder values at levels 1 to 10. */
	[stat: `stat${number}`]: StatArray | undefined;
}

/** One Fairy as generated. */
export interface Fairy {
	/** Upstream `fairy` id, 1 upwards, with the collab fairies starting at 1000. */
	id: number;
	/** Official English name, such as "Warrior Fairy". */
	name: string;
	/** The game's unit code, such as "fighting", which names its asset bundles. */
	code: string;
	/** Type name, such as "Buff". */
	typeName: string;
	/** Whether the skill is a strategy skill (`mission_skill_config`) rather than a battle skill. */
	strategy: boolean;
	/** Short flavour line, `fairy.description` text. */
	tagline: string;
	/** Longer flavour text, `fairy.introduce` text. */
	introduce: string;
	/** How long the Fairy takes to produce, in seconds, or null when it is not producible. */
	productionSeconds: number | null;
	/** How the Fairy is obtained. */
	source: "Production" | "Event" | "Collab";
	/** Base stat values before level and star scaling. */
	stats: FairyStatValues;
	/** The Fairy's own growth multiplier, `fairy.grow`. */
	grow: number;
	/** Star rank multipliers, index 0 is 1 star, index 4 is 5 stars. */
	proportion: number[];
	/** Its one skill, battle or strategy. */
	skill: FairySkill;
}

/** The generated `fairies.json`. */
export interface FairyData {
	/** Constants shared by every Fairy's stats. */
	constants: FairyConstants;
	/** The type names present, in game order, for the filter chips. */
	types: string[];
	/** Every talent, in table order. */
	talents: FairyTalent[];
	/** Every Fairy, by id. */
	items: Fairy[];
}
