/** The HOC data model, generated by `tools/data/import.mjs`. */

import type { RawSkill } from "./tdoll";

/** The four stat keys every HOC has, in display order. */
export type HocStatKey = "lethality" | "pierce" | "precision" | "reload";

/** One value per HOC stat. */
export type HocStatValues = Record<HocStatKey, number>;

/** The game constants every HOC's stats are worked out from. */
export interface HocConstants {
	/** Added to the HOC's level before scaling, from `squad_basic_lv`. */
	baseLevel: number;
	/** The highest level a HOC reaches. */
	maxLevel: number;
	/** Each stat's share of the level-based and chip-based parts, in percent. */
	stats: Record<HocStatKey, { basicRate: number; cpuRate: number }>;
	/** The chip board's strength at 1 to 5 stars, in percent, indexed from 0. */
	starCpuRates: number[];
}

/** One HOC skill. HOC skills never name exclusive equipment, so `equipmentMentions` is absent. */
export type HocSkill = Omit<RawSkill, "equipmentMentions">;

/** One HOC as generated. */
export interface Hoc {
	/** Upstream squad id, 1 upwards. */
	id: number;
	/** Official English name, such as "BGM-71". */
	name: string;
	/** Class name, such as "Anti-Tank Weapon". */
	className: string;
	/** Flavour text about the unit's crew. */
	description: string;
	/** Global release date, `YYYY-MM-DD`. */
	released: string;
	/** How long the unit takes to produce, in seconds. */
	productionSeconds: number;
	/** Support range in nodes. */
	range: number;
	/** The HOC's own share of its level-based stats, in percent. */
	basicRate: number;
	/** The HOC's own share of its chip-based stats, in percent. */
	cpuRate: number;
	/** Each stat's combined rating before level scaling. */
	attributes: HocStatValues;
	/** Its three skills, in game order. */
	skills: HocSkill[];
}

/** The generated `hocs.json`. */
export interface HocData {
	/** Constants shared by every HOC's stats. */
	constants: HocConstants;
	/** The class names present, in game order, for the filter chips. */
	classes: string[];
	/** Every HOC, by id. */
	items: Hoc[];
}
