/** The story data model, generated by `tools/story/build_story.mjs`. */

/** One run of text sharing a style, from the inline markup in a script line. */
export interface StorySpan {
	/** The text itself. */
	text: string;
	/** Inline styles that were open over this run, such as `color` or `size`. Absent when the run is unstyled. */
	style?: Record<string, string>;
}

/** One click-through page of a beat's text. A beat splits into pages where the script wrote a `+`. */
export interface StoryPage {
	/** The styled runs making up the page, in order. */
	spans: StorySpan[];
}

/** A character standing on one side of the stage for a beat. */
export interface StorySprite {
	/** The game's prefab name for the art, such as a doll's code. Used to build the sprite's URL. */
	prefab: string;
	/** Which expression variant of the prefab to show, 0 when the script named none. */
	expression: number;
	/** Which side of the stage the sprite stands on. */
	side: "left" | "right";
	/** Stage directions bound to this sprite rather than the beat, such as `Position` or `Scale`. */
	tags: Record<string, string>;
}

/** A stage direction for a beat: music, a background change, an effect, or a tag the parser did not recognise. */
export interface StoryOp {
	/** The normalised op name, such as `bgm`, `background`, `shake` or `unknown`. */
	type: string;
	/** The tag's value, absent when the tag carried none. */
	value?: string;
	/** The tag's original name, kept so an unrecognised one can still be identified. */
	raw: string;
}

/** One line of a script: who is on stage, what changes, and what is said. */
export interface StoryBeat {
	/** The sprites on stage for this beat. Empty for narration. */
	sprites: StorySprite[];
	/** The stage directions for this beat. */
	ops: StoryOp[];
	/** Who is speaking, or null when the beat is narration or the script named nobody. */
	speaker: string | null;
	/** Whether the script marked this beat as narration. */
	narrator: boolean;
	/** The text, split into click-through pages. Empty when the beat only changes the stage. */
	pages: StoryPage[];
}

/** One script's beats, fetched only when that scene is opened. */
export interface StoryScene {
	/** The script name from the game's index, such as `0-1-1`. */
	name: string;
	/** The beats in order. */
	beats: StoryBeat[];
}

/** One mission inside a chapter, which plays one or more scenes in order. */
export interface StoryMission {
	/** The game's `story_util` row id. */
	id: number;
	/** The mission's name, such as the operation it covers. */
	title: string;
	/** The longer blurb the game shows beside the title. */
	description: string;
	/** The music cue the mission opens with, absent when it names none. */
	bgm?: string;
	/** The background the mission opens on, as the game's own scene code. Absent when it names none. */
	background?: string;
	/** The scripts this mission plays, in order. */
	scripts: string[];
}

/** One chapter's mission list, fetched when the chapter is opened. */
export interface StoryChapter {
	/** The game's `story_playback` row id. */
	id: number;
	/** The missions in order. */
	missions: StoryMission[];
}

/** A chapter as the index lists it, without its missions. */
export interface StoryChapterSummary {
	/** The game's `story_playback` row id, used to fetch the chapter. */
	id: number;
	/** The chapter's number as the game labels it, such as `0` or `5.5`. */
	label: string;
	/** The chapter's name. */
	name: string;
	/** The game's playback type. 1 is a main-story chapter. */
	type: number;
	/** Where the chapter sits in the menu's order. */
	order: number;
	/** How many missions the chapter holds, so the index can say so without fetching it. */
	missions: number;
}

/** The story index: every chapter, without their missions or scenes. */
export interface StoryIndex {
	/** The chapters in menu order. */
	chapters: StoryChapterSummary[];
}
